### get all accounting ###
GET http://localhost:8000/api/chartofaccounting

### get all accounting amount report ###
GET http://localhost:8000/api/chartofaccounting/report

### get one
GET http://localhost:8000/api/chartofaccounting/1

### create a new 
POST http://localhost:8000/api/chartofaccounting
Content-Type: application/json

{
    "code":1000,
    "name":"Inventory",
    "gl_type":"Asset",
    "is_leaf":false,
    "dr_amount":"0.0",
    "cr_amount":"0.0",
    "balance":"0.0"

    # "parent":{
      
    # }
}

### update 
PATCH http://localhost:8000/api/chartofaccounting/1
Content-Type: application/json

{
    "is_leaf":false
}