import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1729769790979 implements MigrationInterface {
    name = 'Initial1729769790979'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`permission\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_240853a0c3353c25fb12434ad3\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, UNIQUE INDEX \`IDX_ae4578dcaed5adff96595e6166\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`first_name\` varchar(255) NOT NULL, \`last_name\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`phone\` varchar(255) NOT NULL, \`address\` varchar(255) NOT NULL, \`isBlocked\` tinyint NOT NULL DEFAULT 0, \`salt\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`username\` varchar(50) NOT NULL, \`image\` varchar(255) NULL, \`page_name\` varchar(255) NULL, \`business_address\` varchar(255) NULL, \`createdat\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedat\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`roleId\` int NULL, UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`daily_balance\` (\`id\` int NOT NULL AUTO_INCREMENT, \`date\` date NOT NULL, \`opening_balance\` decimal NOT NULL, \`closing_balance\` decimal NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`chartOfAccountingId\` int NULL, UNIQUE INDEX \`IDX_a4ab7e41f93098da5954188d54\` (\`date\`, \`chartOfAccountingId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`expense\` (\`id\` int NOT NULL AUTO_INCREMENT, \`description\` varchar(255) NOT NULL, \`amount\` int NOT NULL, \`expenseDate\` datetime NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleteAt\` datetime(6) NULL, \`transactionId\` int NULL, \`createdById\` int NULL, \`updatedById\` int NULL, UNIQUE INDEX \`REL_a285af18f19a8509c41fedd3cf\` (\`transactionId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`transaction\` (\`id\` int NOT NULL AUTO_INCREMENT, \`transaction_date\` datetime NOT NULL, \`description\` varchar(255) NOT NULL, \`total_amount\` double NOT NULL, \`transaction_type\` text NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`journal\` (\`id\` int NOT NULL AUTO_INCREMENT, \`dr_amount\` decimal NOT NULL DEFAULT '0', \`cr_amount\` decimal NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`transactionId\` int NULL, \`glId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ledger\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` int NOT NULL, \`name\` varchar(255) NOT NULL, \`gl_type\` text NOT NULL, \`is_leaf\` tinyint NOT NULL DEFAULT 1, \`dr_amount\` double NOT NULL DEFAULT '0', \`cr_amount\` double NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`mpath\` varchar(255) NULL DEFAULT '', \`parentId\` int NULL, UNIQUE INDEX \`IDX_44c2694ff099e6320ec96d41e4\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customer_payment_plan\` (\`id\` int NOT NULL AUTO_INCREMENT, \`next_payment_date\` datetime NOT NULL, \`paid_on\` datetime NULL, \`customerId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`attribute_set\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`createdById\` int NULL, \`updatedById\` int NULL, UNIQUE INDEX \`IDX_dd1fb3e9842f0a5e52e16beb1f\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`instance\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(80) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`attributeSetId\` int NULL, \`createdById\` int NULL, \`updatedById\` int NULL, UNIQUE INDEX \`IDX_7517ace937bf54b1902089eedf\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`unit\` varchar(255) NOT NULL, \`description\` varchar(255) NULL, \`image\` varchar(255) NULL, \`is_leaf\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`mpath\` varchar(255) NULL DEFAULT '', \`parentId\` int NULL, \`createdById\` int NULL, \`updatedById\` int NULL, UNIQUE INDEX \`IDX_22cc43e9a74d7498546e9a63e7\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sales_item\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` int NOT NULL, \`sellingUnitPrice\` double NOT NULL, \`buyingUnitPrice\` double NOT NULL, \`saleId\` int NULL, \`attributeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`locator\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`status\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`createdById\` int NULL, \`updatedById\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`storage\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` int NOT NULL, \`lot_quantity\` int NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`locatorId\` int NULL, \`pAttributeId\` int NULL, \`createdById\` int NULL, \`updatedById\` int NULL, UNIQUE INDEX \`REL_11854e339a884d15a5a7ad8570\` (\`pAttributeId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`attribute\` (\`id\` int NOT NULL AUTO_INCREMENT, \`sellingUnitPrice\` double NOT NULL DEFAULT '0', \`buyingUnitPrice\` double NOT NULL DEFAULT '0', \`sku\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`productId\` int NULL, \`createdById\` int NULL, \`updatedById\` int NULL, UNIQUE INDEX \`IDX_46620e1005dff8bd60adfe22ee\` (\`sku\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_item\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` int NOT NULL, \`buyingUnitPrice\` double NOT NULL, \`lot_quantity\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`attributeId\` int NULL, \`purchaseId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase\` (\`id\` int NOT NULL AUTO_INCREMENT, \`purchaseDate\` datetime NOT NULL, \`totalAmount\` double NOT NULL, \`invoiceNumber\` varchar(50) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`supplierId\` int NULL, \`deliveryId\` int NULL, \`createdById\` int NULL, \`updatedById\` int NULL, UNIQUE INDEX \`IDX_fe50e0c7a1bc820cae32d27b0e\` (\`invoiceNumber\`), UNIQUE INDEX \`REL_31d9ffbfa840b4df055c361e88\` (\`deliveryId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`delivery\` (\`id\` int NOT NULL AUTO_INCREMENT, \`deliveryDate\` datetime NOT NULL, \`deliveryStatus\` text NOT NULL, \`deliveryAddress\` varchar(255) NOT NULL, \`action\` text NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sale\` (\`id\` int NOT NULL AUTO_INCREMENT, \`totalAmount\` double NOT NULL, \`invoiceNumber\` varchar(50) NOT NULL, \`discount\` int NOT NULL DEFAULT '0', \`salesDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`customerId\` int NULL, \`deliveryId\` int NULL, \`createdById\` int NULL, \`updatedById\` int NULL, UNIQUE INDEX \`IDX_41731786c57be025e851431989\` (\`invoiceNumber\`), UNIQUE INDEX \`REL_bfa3717f3abad5107d587d5823\` (\`deliveryId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customer\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(60) NULL, \`phone\` varchar(13) NOT NULL, \`address\` varchar(255) NULL, \`email\` varchar(255) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`createdById\` int NULL, \`updatedById\` int NULL, UNIQUE INDEX \`IDX_03846b4bae9df80f19c76005a8\` (\`phone\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sale_revenue\` (\`id\` int NOT NULL AUTO_INCREMENT, \`saleId\` int NOT NULL, \`customerId\` int NOT NULL, \`paymentDate\` datetime NOT NULL, \`amountPaid\` double NOT NULL, \`cheque_number\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`accountId\` int NULL, \`parentId\` int NULL, \`createdById\` int NULL, \`updatedById\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`accounts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(80) NOT NULL, \`code\` int NOT NULL, \`account_number\` varchar(80) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`type\` text NULL, \`balance\` decimal NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`chartOfAccountingId\` int NULL, \`createdById\` int NULL, \`updatedById\` int NULL, UNIQUE INDEX \`IDX_490319656e54a7957dc1fed027\` (\`code\`), UNIQUE INDEX \`IDX_1b4121b8a1cf3729f180a82517\` (\`name\`, \`account_number\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payment\` (\`id\` int NOT NULL AUTO_INCREMENT, \`purchaseId\` int NOT NULL, \`supplierId\` int NOT NULL, \`paymentDate\` datetime NOT NULL, \`amountPaid\` double NOT NULL, \`cheque_number\` varchar(255) NULL, \`is_valid\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`accountId\` int NULL, \`parentId\` int NULL, \`createdById\` int NULL, \`updatedById\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`supplier_payment_plan\` (\`id\` int NOT NULL AUTO_INCREMENT, \`next_payment_date\` datetime NOT NULL, \`paid_on\` datetime NULL, \`supplierId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`supplier\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`address\` varchar(255) NOT NULL, \`phone\` varchar(50) NOT NULL, \`email\` varchar(255) NULL, \`owner\` varchar(80) NOT NULL, \`status\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`createdById\` int NULL, \`updatedById\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`token\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`token\` text NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`expired_at\` datetime NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role_permissions\` (\`roleId\` int NOT NULL, \`permissionId\` int NOT NULL, INDEX \`IDX_b4599f8b8f548d35850afa2d12\` (\`roleId\`), INDEX \`IDX_06792d0c62ce6b0203c03643cd\` (\`permissionId\`), PRIMARY KEY (\`roleId\`, \`permissionId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`attribute_instance\` (\`attributeId\` int NOT NULL, \`instanceId\` int NOT NULL, INDEX \`IDX_c9d29aa6367a716d953905534b\` (\`attributeId\`), INDEX \`IDX_5d0a3a1b9bfb343f2b41866905\` (\`instanceId\`), PRIMARY KEY (\`attributeId\`, \`instanceId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_368e146b785b574f42ae9e53d5e\` FOREIGN KEY (\`roleId\`) REFERENCES \`role\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`daily_balance\` ADD CONSTRAINT \`FK_ec89d87fd94ee24e168bfa46253\` FOREIGN KEY (\`chartOfAccountingId\`) REFERENCES \`ledger\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD CONSTRAINT \`FK_a285af18f19a8509c41fedd3cf0\` FOREIGN KEY (\`transactionId\`) REFERENCES \`transaction\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD CONSTRAINT \`FK_33025f4898ea79cc35a3c6da4ca\` FOREIGN KEY (\`createdById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD CONSTRAINT \`FK_106758ff33bf2f0895ccdddfe59\` FOREIGN KEY (\`updatedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`journal\` ADD CONSTRAINT \`FK_2ff763901947cf0c6f7993cca0c\` FOREIGN KEY (\`transactionId\`) REFERENCES \`transaction\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`journal\` ADD CONSTRAINT \`FK_d3159aa8331690c666e71399f79\` FOREIGN KEY (\`glId\`) REFERENCES \`ledger\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ledger\` ADD CONSTRAINT \`FK_10abeada18107d94067c4759b90\` FOREIGN KEY (\`parentId\`) REFERENCES \`ledger\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_payment_plan\` ADD CONSTRAINT \`FK_45ccfdc6b0d7e8c1068bc8b67b9\` FOREIGN KEY (\`customerId\`) REFERENCES \`customer\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute_set\` ADD CONSTRAINT \`FK_d691964bfce84976b244d7e7ffd\` FOREIGN KEY (\`createdById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute_set\` ADD CONSTRAINT \`FK_8dcaed8a7a4d30fcf39bc0fc5d9\` FOREIGN KEY (\`updatedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`instance\` ADD CONSTRAINT \`FK_d44bcbea234f90fdb0b85231aa0\` FOREIGN KEY (\`attributeSetId\`) REFERENCES \`attribute_set\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`instance\` ADD CONSTRAINT \`FK_b6f52d06268b895149359573910\` FOREIGN KEY (\`createdById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`instance\` ADD CONSTRAINT \`FK_7ac42793ef009096e60d8ee17e6\` FOREIGN KEY (\`updatedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product\` ADD CONSTRAINT \`FK_77e467b32f0a8b7a1e5503eecac\` FOREIGN KEY (\`parentId\`) REFERENCES \`product\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product\` ADD CONSTRAINT \`FK_806302f2d4da2a0c27eedbf34fe\` FOREIGN KEY (\`createdById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product\` ADD CONSTRAINT \`FK_9c29670ff9dd3fd43cf20733c19\` FOREIGN KEY (\`updatedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sales_item\` ADD CONSTRAINT \`FK_78b17af3642a95d9012691fa85f\` FOREIGN KEY (\`saleId\`) REFERENCES \`sale\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sales_item\` ADD CONSTRAINT \`FK_cac32e60f3892a54c36ac8ce2ef\` FOREIGN KEY (\`attributeId\`) REFERENCES \`attribute\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`locator\` ADD CONSTRAINT \`FK_880920e21caa6b0ca857b2532d5\` FOREIGN KEY (\`createdById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`locator\` ADD CONSTRAINT \`FK_467a64766cd1308d81e1d566749\` FOREIGN KEY (\`updatedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`storage\` ADD CONSTRAINT \`FK_427bce0633824770ca3a7bc9965\` FOREIGN KEY (\`locatorId\`) REFERENCES \`locator\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`storage\` ADD CONSTRAINT \`FK_11854e339a884d15a5a7ad85709\` FOREIGN KEY (\`pAttributeId\`) REFERENCES \`attribute\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`storage\` ADD CONSTRAINT \`FK_f3b34db35361cb0e49518884b3a\` FOREIGN KEY (\`createdById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`storage\` ADD CONSTRAINT \`FK_a270035df4d58ad13cf6d496077\` FOREIGN KEY (\`updatedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute\` ADD CONSTRAINT \`FK_ed353f134370fc893a07cfd9d1f\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute\` ADD CONSTRAINT \`FK_5f81625b29ba98ea640af8466e3\` FOREIGN KEY (\`createdById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute\` ADD CONSTRAINT \`FK_086e5ade959600ce328af3cf093\` FOREIGN KEY (\`updatedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_item\` ADD CONSTRAINT \`FK_18ade5c2479ea96b01f7355df32\` FOREIGN KEY (\`attributeId\`) REFERENCES \`attribute\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_item\` ADD CONSTRAINT \`FK_29ba18d69c81231e8ffabe478b4\` FOREIGN KEY (\`purchaseId\`) REFERENCES \`purchase\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase\` ADD CONSTRAINT \`FK_b4ee84e23fdff57bb8bfefbf998\` FOREIGN KEY (\`supplierId\`) REFERENCES \`supplier\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase\` ADD CONSTRAINT \`FK_31d9ffbfa840b4df055c361e880\` FOREIGN KEY (\`deliveryId\`) REFERENCES \`delivery\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase\` ADD CONSTRAINT \`FK_c91c01cbbd303cee7a269b24fd1\` FOREIGN KEY (\`createdById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase\` ADD CONSTRAINT \`FK_38435892ee2958b4b0f4c6ad1ed\` FOREIGN KEY (\`updatedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale\` ADD CONSTRAINT \`FK_a742b91c1b99a4269c102d47541\` FOREIGN KEY (\`customerId\`) REFERENCES \`customer\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale\` ADD CONSTRAINT \`FK_bfa3717f3abad5107d587d58232\` FOREIGN KEY (\`deliveryId\`) REFERENCES \`delivery\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale\` ADD CONSTRAINT \`FK_7094c12fb76feea2aaf7d1ee957\` FOREIGN KEY (\`createdById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale\` ADD CONSTRAINT \`FK_d9b993b137fe60a85ae0f6b7e51\` FOREIGN KEY (\`updatedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer\` ADD CONSTRAINT \`FK_06da83f09c12364501434a415f9\` FOREIGN KEY (\`createdById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer\` ADD CONSTRAINT \`FK_c214a79453aea94b16ccba6d9eb\` FOREIGN KEY (\`updatedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_revenue\` ADD CONSTRAINT \`FK_919bbcc650b99f834eba3f2fe10\` FOREIGN KEY (\`saleId\`) REFERENCES \`sale\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_revenue\` ADD CONSTRAINT \`FK_772a2aa952f4de4dd91d13927f6\` FOREIGN KEY (\`customerId\`) REFERENCES \`customer\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_revenue\` ADD CONSTRAINT \`FK_7676a8f9a5ba289bbcbe73c68c7\` FOREIGN KEY (\`accountId\`) REFERENCES \`accounts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_revenue\` ADD CONSTRAINT \`FK_4f9adcff43f7a1c56853c7eb367\` FOREIGN KEY (\`parentId\`) REFERENCES \`sale_revenue\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_revenue\` ADD CONSTRAINT \`FK_8913a43fb0254367bce878931d9\` FOREIGN KEY (\`createdById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_revenue\` ADD CONSTRAINT \`FK_cbb999e1d2bbf8f3913dc3557d0\` FOREIGN KEY (\`updatedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`accounts\` ADD CONSTRAINT \`FK_2f7a0cafb252fff3776b63924ed\` FOREIGN KEY (\`chartOfAccountingId\`) REFERENCES \`ledger\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`accounts\` ADD CONSTRAINT \`FK_9b0715a70263bfd2144bb6c151d\` FOREIGN KEY (\`createdById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`accounts\` ADD CONSTRAINT \`FK_6bbe30905bb893c1aa2818690c2\` FOREIGN KEY (\`updatedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment\` ADD CONSTRAINT \`FK_885283e0709e1a736ecca80cf3c\` FOREIGN KEY (\`purchaseId\`) REFERENCES \`purchase\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment\` ADD CONSTRAINT \`FK_a3772a91be111b4b6a8a496fffa\` FOREIGN KEY (\`supplierId\`) REFERENCES \`supplier\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment\` ADD CONSTRAINT \`FK_25ee41d829b06c6e7451b89037f\` FOREIGN KEY (\`accountId\`) REFERENCES \`accounts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment\` ADD CONSTRAINT \`FK_375b2e9ed6ac1bbc566cbd22dc1\` FOREIGN KEY (\`parentId\`) REFERENCES \`payment\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment\` ADD CONSTRAINT \`FK_96605f6105703f10a1a00158d53\` FOREIGN KEY (\`createdById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment\` ADD CONSTRAINT \`FK_fa4a6e31bcb86ab9446a13a2351\` FOREIGN KEY (\`updatedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplier_payment_plan\` ADD CONSTRAINT \`FK_a0be7457f75b4839dec2e185141\` FOREIGN KEY (\`supplierId\`) REFERENCES \`supplier\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplier\` ADD CONSTRAINT \`FK_3c6f83f045f7d82781583ae0885\` FOREIGN KEY (\`createdById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplier\` ADD CONSTRAINT \`FK_81cbac4a5de75dfe0b3c077299d\` FOREIGN KEY (\`updatedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_b4599f8b8f548d35850afa2d12c\` FOREIGN KEY (\`roleId\`) REFERENCES \`role\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_06792d0c62ce6b0203c03643cdd\` FOREIGN KEY (\`permissionId\`) REFERENCES \`permission\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute_instance\` ADD CONSTRAINT \`FK_c9d29aa6367a716d953905534bd\` FOREIGN KEY (\`attributeId\`) REFERENCES \`attribute\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`attribute_instance\` ADD CONSTRAINT \`FK_5d0a3a1b9bfb343f2b418669053\` FOREIGN KEY (\`instanceId\`) REFERENCES \`instance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`attribute_instance\` DROP FOREIGN KEY \`FK_5d0a3a1b9bfb343f2b418669053\``);
        await queryRunner.query(`ALTER TABLE \`attribute_instance\` DROP FOREIGN KEY \`FK_c9d29aa6367a716d953905534bd\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_06792d0c62ce6b0203c03643cdd\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_b4599f8b8f548d35850afa2d12c\``);
        await queryRunner.query(`ALTER TABLE \`supplier\` DROP FOREIGN KEY \`FK_81cbac4a5de75dfe0b3c077299d\``);
        await queryRunner.query(`ALTER TABLE \`supplier\` DROP FOREIGN KEY \`FK_3c6f83f045f7d82781583ae0885\``);
        await queryRunner.query(`ALTER TABLE \`supplier_payment_plan\` DROP FOREIGN KEY \`FK_a0be7457f75b4839dec2e185141\``);
        await queryRunner.query(`ALTER TABLE \`payment\` DROP FOREIGN KEY \`FK_fa4a6e31bcb86ab9446a13a2351\``);
        await queryRunner.query(`ALTER TABLE \`payment\` DROP FOREIGN KEY \`FK_96605f6105703f10a1a00158d53\``);
        await queryRunner.query(`ALTER TABLE \`payment\` DROP FOREIGN KEY \`FK_375b2e9ed6ac1bbc566cbd22dc1\``);
        await queryRunner.query(`ALTER TABLE \`payment\` DROP FOREIGN KEY \`FK_25ee41d829b06c6e7451b89037f\``);
        await queryRunner.query(`ALTER TABLE \`payment\` DROP FOREIGN KEY \`FK_a3772a91be111b4b6a8a496fffa\``);
        await queryRunner.query(`ALTER TABLE \`payment\` DROP FOREIGN KEY \`FK_885283e0709e1a736ecca80cf3c\``);
        await queryRunner.query(`ALTER TABLE \`accounts\` DROP FOREIGN KEY \`FK_6bbe30905bb893c1aa2818690c2\``);
        await queryRunner.query(`ALTER TABLE \`accounts\` DROP FOREIGN KEY \`FK_9b0715a70263bfd2144bb6c151d\``);
        await queryRunner.query(`ALTER TABLE \`accounts\` DROP FOREIGN KEY \`FK_2f7a0cafb252fff3776b63924ed\``);
        await queryRunner.query(`ALTER TABLE \`sale_revenue\` DROP FOREIGN KEY \`FK_cbb999e1d2bbf8f3913dc3557d0\``);
        await queryRunner.query(`ALTER TABLE \`sale_revenue\` DROP FOREIGN KEY \`FK_8913a43fb0254367bce878931d9\``);
        await queryRunner.query(`ALTER TABLE \`sale_revenue\` DROP FOREIGN KEY \`FK_4f9adcff43f7a1c56853c7eb367\``);
        await queryRunner.query(`ALTER TABLE \`sale_revenue\` DROP FOREIGN KEY \`FK_7676a8f9a5ba289bbcbe73c68c7\``);
        await queryRunner.query(`ALTER TABLE \`sale_revenue\` DROP FOREIGN KEY \`FK_772a2aa952f4de4dd91d13927f6\``);
        await queryRunner.query(`ALTER TABLE \`sale_revenue\` DROP FOREIGN KEY \`FK_919bbcc650b99f834eba3f2fe10\``);
        await queryRunner.query(`ALTER TABLE \`customer\` DROP FOREIGN KEY \`FK_c214a79453aea94b16ccba6d9eb\``);
        await queryRunner.query(`ALTER TABLE \`customer\` DROP FOREIGN KEY \`FK_06da83f09c12364501434a415f9\``);
        await queryRunner.query(`ALTER TABLE \`sale\` DROP FOREIGN KEY \`FK_d9b993b137fe60a85ae0f6b7e51\``);
        await queryRunner.query(`ALTER TABLE \`sale\` DROP FOREIGN KEY \`FK_7094c12fb76feea2aaf7d1ee957\``);
        await queryRunner.query(`ALTER TABLE \`sale\` DROP FOREIGN KEY \`FK_bfa3717f3abad5107d587d58232\``);
        await queryRunner.query(`ALTER TABLE \`sale\` DROP FOREIGN KEY \`FK_a742b91c1b99a4269c102d47541\``);
        await queryRunner.query(`ALTER TABLE \`purchase\` DROP FOREIGN KEY \`FK_38435892ee2958b4b0f4c6ad1ed\``);
        await queryRunner.query(`ALTER TABLE \`purchase\` DROP FOREIGN KEY \`FK_c91c01cbbd303cee7a269b24fd1\``);
        await queryRunner.query(`ALTER TABLE \`purchase\` DROP FOREIGN KEY \`FK_31d9ffbfa840b4df055c361e880\``);
        await queryRunner.query(`ALTER TABLE \`purchase\` DROP FOREIGN KEY \`FK_b4ee84e23fdff57bb8bfefbf998\``);
        await queryRunner.query(`ALTER TABLE \`purchase_item\` DROP FOREIGN KEY \`FK_29ba18d69c81231e8ffabe478b4\``);
        await queryRunner.query(`ALTER TABLE \`purchase_item\` DROP FOREIGN KEY \`FK_18ade5c2479ea96b01f7355df32\``);
        await queryRunner.query(`ALTER TABLE \`attribute\` DROP FOREIGN KEY \`FK_086e5ade959600ce328af3cf093\``);
        await queryRunner.query(`ALTER TABLE \`attribute\` DROP FOREIGN KEY \`FK_5f81625b29ba98ea640af8466e3\``);
        await queryRunner.query(`ALTER TABLE \`attribute\` DROP FOREIGN KEY \`FK_ed353f134370fc893a07cfd9d1f\``);
        await queryRunner.query(`ALTER TABLE \`storage\` DROP FOREIGN KEY \`FK_a270035df4d58ad13cf6d496077\``);
        await queryRunner.query(`ALTER TABLE \`storage\` DROP FOREIGN KEY \`FK_f3b34db35361cb0e49518884b3a\``);
        await queryRunner.query(`ALTER TABLE \`storage\` DROP FOREIGN KEY \`FK_11854e339a884d15a5a7ad85709\``);
        await queryRunner.query(`ALTER TABLE \`storage\` DROP FOREIGN KEY \`FK_427bce0633824770ca3a7bc9965\``);
        await queryRunner.query(`ALTER TABLE \`locator\` DROP FOREIGN KEY \`FK_467a64766cd1308d81e1d566749\``);
        await queryRunner.query(`ALTER TABLE \`locator\` DROP FOREIGN KEY \`FK_880920e21caa6b0ca857b2532d5\``);
        await queryRunner.query(`ALTER TABLE \`sales_item\` DROP FOREIGN KEY \`FK_cac32e60f3892a54c36ac8ce2ef\``);
        await queryRunner.query(`ALTER TABLE \`sales_item\` DROP FOREIGN KEY \`FK_78b17af3642a95d9012691fa85f\``);
        await queryRunner.query(`ALTER TABLE \`product\` DROP FOREIGN KEY \`FK_9c29670ff9dd3fd43cf20733c19\``);
        await queryRunner.query(`ALTER TABLE \`product\` DROP FOREIGN KEY \`FK_806302f2d4da2a0c27eedbf34fe\``);
        await queryRunner.query(`ALTER TABLE \`product\` DROP FOREIGN KEY \`FK_77e467b32f0a8b7a1e5503eecac\``);
        await queryRunner.query(`ALTER TABLE \`instance\` DROP FOREIGN KEY \`FK_7ac42793ef009096e60d8ee17e6\``);
        await queryRunner.query(`ALTER TABLE \`instance\` DROP FOREIGN KEY \`FK_b6f52d06268b895149359573910\``);
        await queryRunner.query(`ALTER TABLE \`instance\` DROP FOREIGN KEY \`FK_d44bcbea234f90fdb0b85231aa0\``);
        await queryRunner.query(`ALTER TABLE \`attribute_set\` DROP FOREIGN KEY \`FK_8dcaed8a7a4d30fcf39bc0fc5d9\``);
        await queryRunner.query(`ALTER TABLE \`attribute_set\` DROP FOREIGN KEY \`FK_d691964bfce84976b244d7e7ffd\``);
        await queryRunner.query(`ALTER TABLE \`customer_payment_plan\` DROP FOREIGN KEY \`FK_45ccfdc6b0d7e8c1068bc8b67b9\``);
        await queryRunner.query(`ALTER TABLE \`ledger\` DROP FOREIGN KEY \`FK_10abeada18107d94067c4759b90\``);
        await queryRunner.query(`ALTER TABLE \`journal\` DROP FOREIGN KEY \`FK_d3159aa8331690c666e71399f79\``);
        await queryRunner.query(`ALTER TABLE \`journal\` DROP FOREIGN KEY \`FK_2ff763901947cf0c6f7993cca0c\``);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP FOREIGN KEY \`FK_106758ff33bf2f0895ccdddfe59\``);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP FOREIGN KEY \`FK_33025f4898ea79cc35a3c6da4ca\``);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP FOREIGN KEY \`FK_a285af18f19a8509c41fedd3cf0\``);
        await queryRunner.query(`ALTER TABLE \`daily_balance\` DROP FOREIGN KEY \`FK_ec89d87fd94ee24e168bfa46253\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_368e146b785b574f42ae9e53d5e\``);
        await queryRunner.query(`DROP INDEX \`IDX_5d0a3a1b9bfb343f2b41866905\` ON \`attribute_instance\``);
        await queryRunner.query(`DROP INDEX \`IDX_c9d29aa6367a716d953905534b\` ON \`attribute_instance\``);
        await queryRunner.query(`DROP TABLE \`attribute_instance\``);
        await queryRunner.query(`DROP INDEX \`IDX_06792d0c62ce6b0203c03643cd\` ON \`role_permissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_b4599f8b8f548d35850afa2d12\` ON \`role_permissions\``);
        await queryRunner.query(`DROP TABLE \`role_permissions\``);
        await queryRunner.query(`DROP TABLE \`token\``);
        await queryRunner.query(`DROP TABLE \`supplier\``);
        await queryRunner.query(`DROP TABLE \`supplier_payment_plan\``);
        await queryRunner.query(`DROP TABLE \`payment\``);
        await queryRunner.query(`DROP INDEX \`IDX_1b4121b8a1cf3729f180a82517\` ON \`accounts\``);
        await queryRunner.query(`DROP INDEX \`IDX_490319656e54a7957dc1fed027\` ON \`accounts\``);
        await queryRunner.query(`DROP TABLE \`accounts\``);
        await queryRunner.query(`DROP TABLE \`sale_revenue\``);
        await queryRunner.query(`DROP INDEX \`IDX_03846b4bae9df80f19c76005a8\` ON \`customer\``);
        await queryRunner.query(`DROP TABLE \`customer\``);
        await queryRunner.query(`DROP INDEX \`REL_bfa3717f3abad5107d587d5823\` ON \`sale\``);
        await queryRunner.query(`DROP INDEX \`IDX_41731786c57be025e851431989\` ON \`sale\``);
        await queryRunner.query(`DROP TABLE \`sale\``);
        await queryRunner.query(`DROP TABLE \`delivery\``);
        await queryRunner.query(`DROP INDEX \`REL_31d9ffbfa840b4df055c361e88\` ON \`purchase\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe50e0c7a1bc820cae32d27b0e\` ON \`purchase\``);
        await queryRunner.query(`DROP TABLE \`purchase\``);
        await queryRunner.query(`DROP TABLE \`purchase_item\``);
        await queryRunner.query(`DROP INDEX \`IDX_46620e1005dff8bd60adfe22ee\` ON \`attribute\``);
        await queryRunner.query(`DROP TABLE \`attribute\``);
        await queryRunner.query(`DROP INDEX \`REL_11854e339a884d15a5a7ad8570\` ON \`storage\``);
        await queryRunner.query(`DROP TABLE \`storage\``);
        await queryRunner.query(`DROP TABLE \`locator\``);
        await queryRunner.query(`DROP TABLE \`sales_item\``);
        await queryRunner.query(`DROP INDEX \`IDX_22cc43e9a74d7498546e9a63e7\` ON \`product\``);
        await queryRunner.query(`DROP TABLE \`product\``);
        await queryRunner.query(`DROP INDEX \`IDX_7517ace937bf54b1902089eedf\` ON \`instance\``);
        await queryRunner.query(`DROP TABLE \`instance\``);
        await queryRunner.query(`DROP INDEX \`IDX_dd1fb3e9842f0a5e52e16beb1f\` ON \`attribute_set\``);
        await queryRunner.query(`DROP TABLE \`attribute_set\``);
        await queryRunner.query(`DROP TABLE \`customer_payment_plan\``);
        await queryRunner.query(`DROP INDEX \`IDX_44c2694ff099e6320ec96d41e4\` ON \`ledger\``);
        await queryRunner.query(`DROP TABLE \`ledger\``);
        await queryRunner.query(`DROP TABLE \`journal\``);
        await queryRunner.query(`DROP TABLE \`transaction\``);
        await queryRunner.query(`DROP INDEX \`REL_a285af18f19a8509c41fedd3cf\` ON \`expense\``);
        await queryRunner.query(`DROP TABLE \`expense\``);
        await queryRunner.query(`DROP INDEX \`IDX_a4ab7e41f93098da5954188d54\` ON \`daily_balance\``);
        await queryRunner.query(`DROP TABLE \`daily_balance\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_ae4578dcaed5adff96595e6166\` ON \`role\``);
        await queryRunner.query(`DROP TABLE \`role\``);
        await queryRunner.query(`DROP INDEX \`IDX_240853a0c3353c25fb12434ad3\` ON \`permission\``);
        await queryRunner.query(`DROP TABLE \`permission\``);
    }

}
