@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhZ2liIiwidXNlcklkIjoxLCJyb2xlIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4iLCJkZXNjcmlwdGlvbiI6IkFkbWluaXN0cmF0b3Igd2l0aCBmdWxsIGFjY2VzcyIsImlzX2FjdGl2ZSI6dHJ1ZX0sImlhdCI6MTczMDAwMzg1NywiZXhwIjoxNzMwMDA3NDU3fQ._-QiyaTWky62bJGWUcAYI7R2cpANyvWscPSxJ3UjyVI
### Sign in a User ####
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "username":"ragib",
    "password": "Ragib@06#"
}

### Get all Purchase history ###
GET http://localhost:8000/api/purchase
Authorization:Bearer {{token}}

### Get a Purchase history ###
GET http://localhost:8000/api/purchase/1


### Create a purchase ###
POST http://localhost:8000/api/purchase
Content-Type: application/json

{
  "supplier": {
"id":1
},
  "purchaseDate": "2024-07-01T16:35:50.274Z",
  "totalAmount": "12354.35",
  "invoiceNumber": "2357",
  "purchaseItems": [
    {
"attribute":{"id":1},
"quantity":125,
"buyingUnitPrice":"130.22"
}
  ],
  "payment": [
    {
"account":{"id":2},
"paymentDate":"2024-07-01T16:35:50.274Z",
"amountPaid":"1280",
"supplier": {
"id":1
}
}
  ]
}


#### Delete a purchase ###
DELETE http://localhost:8000/api/purchase/1