###Create
POST http://localhost:5000/api/attachment
Content-Type: application/json

{
    "original": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/902/offer-5.png",
        "thumbnail": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/902/conversions/offer-5-thumbnail.jpg",
        "typeId":1
}

###GET all 
GET http://localhost:5000/api/attachment