@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJAZ21haWwuY29tIiwicm9sZSI6eyJjcmVhdGVkX2F0IjoiMjAyMy0wMy0zMVQxMzo0MzozNi4yMTlaIiwidXBkYXRlZF9hdCI6IjIwMjMtMDMtMzFUMTM6NDM6MzYuMjE5WiIsImlkIjoxLCJuYW1lIjoic3VwZXJfYWRtaW4iLCJwZXJtaXR0ZWRfcGFnZSI6W3siaWQiOjEsIm5hbWUiOiJ2aWV3X3JvbGUifSx7ImlkIjoyLCJuYW1lIjoiY3JlYXRlX3JvbGUifSx7ImlkIjozLCJuYW1lIjoidXBkYXRlX3JvbGUifSx7ImlkIjo0LCJuYW1lIjoiZGVsZXRlX3JvbGUifSx7ImlkIjo1LCJuYW1lIjoidmlld190eXBlIn0seyJpZCI6NiwibmFtZSI6ImNyZWF0ZV90eXBlIn0seyJpZCI6NywibmFtZSI6InVwZGF0ZV90eXBlIn0seyJpZCI6OCwibmFtZSI6ImRlbGV0ZV90eXBlIn0seyJpZCI6OSwibmFtZSI6InZpZXdfY2F0ZWdvcnkifSx7ImlkIjoxMCwibmFtZSI6ImNyZWF0ZV9jYXRlZ29yeSJ9XX0sImlzX2FjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjgwNzY5MTQ4LCJleHAiOjE2ODA3NzI3NDh9.2puI_C9HS-1_Jynt6dExvhLt0YuLZZiQzE2xgrdBrj8

###Login
Post http://localhost:5000/api/token
Content-Type: application/json

{
    "email":"r@gmail.com",
    "password":"test123"
}
### Catagories
GET http://localhost:5000/api/categories?limit=15&page=1
Authorization:Bearer {{token}}

### New Catagory
POST http://localhost:5000/api/categories
Content-Type: application/json

{
    "name": "Fruits & Vegetables",
    "slug": "fruits-vegetables",
    "icon": "FruitsVegetable",
    "image": [],
    "details": null,
    "language": "en",
    "translated_languages": [
      "en"
    ],
    
    
}


###Update category
